import requests
import time

url = "https://tronb2.vercel.app/"
interval = 0

while True:
    resporihj = requests.get(url)
    resporihj1 = requests.get(url)
    respori2 = requests.get(url)
    respori3 = requests.get(url)
    respori4 =requests.get(url)
    respori = requests.get(url)
    respo1 = requests.get(url)
    respo2 = requests.get(url)
    respo3 = requests.get(url)
    respo4 =requests.get(url)
    rehspoyuiku = requests.get(url)
    respoyui1 = requests.get(url)
    respoyui2 = requests.get(url)
    respoyui3 = requests.get(url)
    respoyui4 =requests.get(url)
    rehjmspoyui = requests.get(url)
    rehjmspoyui1 = requests.get(url)
    rehjmspoyui2 = requests.get(url)
    rehjmspoyui3 = requests.get(url)
    rehspoyui4 =requests.get(url)
    rehspoyui = requests.get(url)
    rehspoyui1 = requests.get(url)
    rehspoyui2 = requests.get(url)
    rehspoyui3 = requests.get(url)
    rehspoyuiku4 =requests.get(url)
    respodr = requests.get(url)
    respodr1 = requests.get(url)
    respodr2 = requests.get(url)
    respodr3 = requests.get(url)
    respodr4 =requests.get(url)
    respodri = requests.get(url)
    respodri1 = requests.get(url)
    respodri2 = requests.get(url)
    respodri3 = requests.get(url)
    respodri4 =requests.get(url)
    respodrihj0 = requests.get(url)
    respodrihj10 = requests.get(url)
    respodrihj20 = requests.get(url)
    respodrihj30 = requests.get(url)
    resporihj40 =requests.get(url)
    print(resporihj.json())
    time.sleep(interval)
